package io.aequicor.heartbeat.feature.harness.api

import kotlinx.serialization.Serializable
import kotlin.jvm.JvmInline

/** Profile-local identity generated by the host before submitting a library mutation. */
@Serializable
@JvmInline
public value class HarnessId(public val value: String) {
    init {
        require(value.isNotBlank())
    }
}

/** Immutable slug used in hs_* tools and custom.harness.* event names. */
@Serializable
@JvmInline
public value class HarnessName(public val value: String) {
    init {
        require(value.matches(Regex("[a-z][a-z0-9_]{1,19}")))
    }
}

/** Identity of one item, stable across text and code revisions. */
@Serializable
@JvmInline
public value class ItemId(public val value: String) {
    init {
        require(value.isNotBlank())
    }
}

/** Immutable item slug; unique within its harness. */
@Serializable
@JvmInline
public value class ItemName(public val value: String) {
    init {
        require(value.matches(Regex("[a-z][a-z0-9_]{0,31}")))
    }
}
