package io.aequicor.heartbeat.feature.harness.api.workflow

import io.aequicor.heartbeat.feature.aiengine.facade.api.PermissionRequest
import io.aequicor.heartbeat.feature.aiengine.facade.api.SessionRef
import io.aequicor.heartbeat.feature.harness.api.HarnessId
import io.aequicor.heartbeat.feature.harness.api.HarnessLimits
import io.aequicor.heartbeat.feature.harness.api.ItemId
import io.aequicor.heartbeat.feature.harness.api.ItemName
import io.aequicor.heartbeat.feature.scheduler.api.ActionId
import io.aequicor.heartbeat.feature.scheduler.api.WakeId
import kotlinx.serialization.Serializable
import kotlinx.serialization.Transient
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlin.time.Instant

/** A scheduler-compatible action id generated by the caller before registering its completion wake. */
@Serializable
public data class RunId(val value: String) {
    init {
        require(value.startsWith(RUN_PREFIX) && value.length > RUN_PREFIX.length)
        ActionId(value)
    }

    /** Identity used by helper leases and the durable completion outbox. */
    public val action: ActionId get() = ActionId(value)
}

/** Executable snapshot retained through library edits and process restarts. */
@Serializable
public data class PinnedWorkflow(
    val source: String,
    val sourceSha: String,
    val harnessRevision: Long,
    val renderedItems: Map<ItemName, String>,
) {
    init {
        require(source.length <= HarnessLimits.SOURCE_CHARS)
        require(isWorkflowDigest(sourceSha))
        require(harnessRevision >= 0)
        require(renderedItems.size <= HarnessLimits.ITEMS)
        require(renderedItems.values.all { it.length <= HarnessLimits.SOURCE_CHARS })
    }

    override fun toString(): String = "PinnedWorkflow(revision=$harnessRevision, ***)"
}

/** Why execution started; script starts are covered by approval of the script code. */
@Serializable
public enum class WorkflowOrigin { Agent, Script }

/** Stable failure categories used by the journal and replay, without exception text. */
@Serializable
public enum class WorkflowFailure { Diverged, Interrupted, Timeout, Cancelled, Error }

/** Durable outcome; Running includes cancellation awaiting confirmed helper cleanup. */
@Serializable
public sealed interface WorkflowStatus {
    /** Execution or confirmed-stop reconciliation is still in progress. */
    @Serializable
    public data object Running : WorkflowStatus

    /** Immutable bounded JSON workflow result. */
    @Serializable
    public data class Completed(val result: JsonElement) : WorkflowStatus {
        init {
            require(result.toString().length <= HarnessLimits.RESULT_CHARS)
        }

        override fun toString(): String = "Completed(***)"
    }

    /** Immutable typed failure without sensitive exception content. */
    @Serializable
    public data class Failed(val reason: WorkflowFailure) : WorkflowStatus
}

/**
 * Durable workflow journal projection. The driver saves changes before native submission and before sending
 * machine feedback. [driverGeneration] fences stale drivers. [cancellation] retains Running capacity until
 * StopRun has durable proof that every helper is settled. Permission requests are reconstructed, never persisted.
 */
@Serializable
public data class WorkflowRun(
    val id: RunId,
    val harness: HarnessId,
    val workflow: ItemId,
    val pinned: PinnedWorkflow,
    val input: JsonObject,
    val caller: SessionRef?,
    val origin: WorkflowOrigin,
    val startedAt: Instant,
    val deadline: Instant,
    val attempt: Int = 0,
    val driverGeneration: Long = 0,
    val status: WorkflowStatus = WorkflowStatus.Running,
    val steps: List<WorkflowStep> = emptyList(),
    @Transient val awaiting: Map<SessionRef, List<PermissionRequest>> = emptyMap(),
    val wake: WakeId? = null,
    val cancellation: WorkflowFailure? = null,
    val finishedAt: Instant? = null,
) {
    init {
        require(deadline > startedAt && deadline - startedAt <= HarnessLimits.RUN_TIME)
        require(attempt >= 0 && driverGeneration >= 0)
        require(steps.size <= HarnessLimits.STEPS && steps.map { it.key }.distinct().size == steps.size)
        require((status == WorkflowStatus.Running) == (finishedAt == null))
        require(finishedAt == null || finishedAt >= startedAt)
    }

    override fun toString(): String = "WorkflowRun(id=$id, generation=$driverGeneration, " +
        "status=${status::class.simpleName.orEmpty()}, ***)"
}

/** A trusted UI caller or the exact session that launched the workflow. */
public sealed interface WorkflowViewer {
    /** Local user with access to every run in this profile. */
    public data object User : WorkflowViewer

    /** Exact native session identity of a tool caller. */
    public data class Agent(val session: SessionRef) : WorkflowViewer
}

/** Tools must apply this check before disclosing status or cancelling a run; machine state is host-internal. */
public fun WorkflowRun.isVisibleTo(viewer: WorkflowViewer): Boolean = when (viewer) {
    WorkflowViewer.User -> true
    is WorkflowViewer.Agent -> caller == viewer.session
}

internal fun isWorkflowDigest(value: String): Boolean =
    value.length == DIGEST_LENGTH && value.all { it in '0'..'9' || it in 'a'..'f' }

private const val RUN_PREFIX = "wf_"
private const val DIGEST_LENGTH = 64
